package com.employee;
// Generated Sep 26, 2016 7:15:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PrimaryInformation generated by hbm2java
 */
public class PrimaryInformation  implements java.io.Serializable {


     private int id;
     private String fname;
     private String lnmame;
     private String email;
     private String password;
     private Set secondaryInformations = new HashSet(0);

    public PrimaryInformation() {
    }

	
    public PrimaryInformation(int id, String fname, String lnmame, String password) {
        this.id = id;
        this.fname = fname;
        this.lnmame = lnmame;
        this.password = password;
    }
    public PrimaryInformation(int id, String fname, String lnmame, String email, String password, Set secondaryInformations) {
       this.id = id;
       this.fname = fname;
       this.lnmame = lnmame;
       this.email = email;
       this.password = password;
       this.secondaryInformations = secondaryInformations;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLnmame() {
        return this.lnmame;
    }
    
    public void setLnmame(String lnmame) {
        this.lnmame = lnmame;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getSecondaryInformations() {
        return this.secondaryInformations;
    }
    
    public void setSecondaryInformations(Set secondaryInformations) {
        this.secondaryInformations = secondaryInformations;
    }




}


